### ISSUE TITLE
Im getting a TypeError: connection.model is not a function when using useMongoClient

### ISSUE THREAD

**Issue by andrewkamphuis** [chevex-archived/mongoose-auto-increment#70]
This
```
const connection = mongoose.connect(config.database.url, { useMongoClient: true });
autoIncrement.initialize(connection);
```
results in TypeError: connection.model is not a function

--

However it works if I don't pass any options into the connection string like this.
```
const connection = mongoose.connect(config.database.url);
autoIncrement.initialize(connection);
```

**Comment by lucduong** [comment]
I am facing the same problem. :(

**Comment by andrewkamphuis** [comment]
Issue resolved - try:

```
mongoose.connect(config.database.url, { useMongoClient: true })
  .then(connection => autoIncrement.initialize(connection));
```

**Comment by ankibalyan** [comment]
This doesn't work when my schema are defined in multiple files, and tried to use autoincrement, it gets failed with Error `Error: mongoose-auto-increment has not been initialized`.
