### ISSUE TITLE
 The field 'index' is not valid for an index specification. 

### ISSUE THREAD

**Issue by jaffarc** [chevex-archived/mongoose-auto-increment#76]
I am having the following error on the server this normal on my local pc is giving the error. all settings are the same

`(node:5863) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: The field 'index' is not valid for an index specification. Specification: { ns: "db.identitycounters", key: { field: 1, model: 1 }, name: "field_1_model_1", unique: true, index: -1, background: true }
(node:5863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by nodkz** [comment]
Fixed in https://github.com/nodkz/mongoose-plugin-autoinc
